SELECT
  tagname,
  COUNT(*) AS row_count
FROM timeseries.v_raw
WHERE timestamp_utc >= TIMESTAMP '2025-11-09 00:00:00'
  AND timestamp_utc <= TIMESTAMP '2025-11-09 23:59:59'
  AND tagname IN (
    'Leg1_ChordA_Motor1_Loadcell_ActLoad',
    'Leg1_ChordA_Motor2_Loadcell_ActLoad',
    'Leg1_ChordA_Motor3_Loadcell_ActLoad',
    'Leg1_ChordA_Motor4_Loadcell_ActLoad',
    'Leg1_ChordA_Motor5_Loadcell_ActLoad',
    'Leg1_ChordA_Motor6_Loadcell_ActLoad',
    'Leg1_ChordA_Motor7_Loadcell_ActLoad',
    'Leg1_ChordA_Motor8_Loadcell_ActLoad',
    'Leg1_ChordB_Motor1_Loadcell_ActLoad',
    'Leg1_ChordB_Motor2_Loadcell_ActLoad',
    'Leg1_ChordB_Motor3_Loadcell_ActLoad',
    'Leg1_ChordB_Motor4_Loadcell_ActLoad',
    'Leg1_ChordB_Motor5_Loadcell_ActLoad',
    'Leg1_ChordB_Motor6_Loadcell_ActLoad',
    'Leg1_ChordB_Motor7_Loadcell_ActLoad',
    'Leg1_ChordB_Motor8_Loadcell_ActLoad',
    'Leg1_ChordC_Motor1_Loadcell_ActLoad',
    'Leg1_ChordC_Motor2_Loadcell_ActLoad',
    'Leg1_ChordC_Motor3_Loadcell_ActLoad',
    'Leg1_ChordC_Motor4_Loadcell_ActLoad',
    'Leg1_ChordC_Motor5_Loadcell_ActLoad',
    'Leg1_ChordC_Motor6_Loadcell_ActLoad',
    'Leg1_ChordC_Motor7_Loadcell_ActLoad',
    'Leg1_ChordC_Motor8_Loadcell_ActLoad',
    'Leg2_ChordA_Motor1_Loadcell_ActLoad',
    'Leg2_ChordA_Motor2_Loadcell_ActLoad',
    'Leg2_ChordA_Motor3_Loadcell_ActLoad',
    'Leg2_ChordA_Motor4_Loadcell_ActLoad',
    'Leg2_ChordA_Motor5_Loadcell_ActLoad',
    'Leg2_ChordA_Motor6_Loadcell_ActLoad',
    'Leg2_ChordA_Motor7_Loadcell_ActLoad',
    'Leg2_ChordA_Motor8_Loadcell_ActLoad',
    'Leg2_ChordB_Motor1_Loadcell_ActLoad',
    'Leg2_ChordB_Motor2_Loadcell_ActLoad',
    'Leg2_ChordB_Motor3_Loadcell_ActLoad',
    'Leg2_ChordB_Motor4_Loadcell_ActLoad',
    'Leg2_ChordB_Motor5_Loadcell_ActLoad',
    'Leg2_ChordB_Motor6_Loadcell_ActLoad',
    'Leg2_ChordB_Motor7_Loadcell_ActLoad',
    'Leg2_ChordB_Motor8_Loadcell_ActLoad',
    'Leg2_ChordC_Motor1_Loadcell_ActLoad',
    'Leg2_ChordC_Motor2_Loadcell_ActLoad',
    'Leg2_ChordC_Motor3_Loadcell_ActLoad',
    'Leg2_ChordC_Motor4_Loadcell_ActLoad',
    'Leg2_ChordC_Motor5_Loadcell_ActLoad',
    'Leg2_ChordC_Motor6_Loadcell_ActLoad',
    'Leg2_ChordC_Motor7_Loadcell_ActLoad',
    'Leg2_ChordC_Motor8_Loadcell_ActLoad',
    'Leg3_ChordA_Motor1_Loadcell_ActLoad',
    'Leg3_ChordA_Motor2_Loadcell_ActLoad',
    'Leg3_ChordA_Motor3_Loadcell_ActLoad',
    'Leg3_ChordA_Motor4_Loadcell_ActLoad',
    'Leg3_ChordA_Motor5_Loadcell_ActLoad',
    'Leg3_ChordA_Motor6_Loadcell_ActLoad',
    'Leg3_ChordA_Motor7_Loadcell_ActLoad',
    'Leg3_ChordA_Motor8_Loadcell_ActLoad',
    'Leg3_ChordB_Motor1_Loadcell_ActLoad',
    'Leg3_ChordB_Motor2_Loadcell_ActLoad',
    'Leg3_ChordB_Motor3_Loadcell_ActLoad',
    'Leg3_ChordB_Motor4_Loadcell_ActLoad',
    'Leg3_ChordB_Motor5_Loadcell_ActLoad',
    'Leg3_ChordB_Motor6_Loadcell_ActLoad',
    'Leg3_ChordB_Motor7_Loadcell_ActLoad',
    'Leg3_ChordB_Motor8_Loadcell_ActLoad',
    'Leg3_ChordC_Motor1_Loadcell_ActLoad',
    'Leg3_ChordC_Motor2_Loadcell_ActLoad',
    'Leg3_ChordC_Motor3_Loadcell_ActLoad',
    'Leg3_ChordC_Motor4_Loadcell_ActLoad',
    'Leg3_ChordC_Motor5_Loadcell_ActLoad',
    'Leg3_ChordC_Motor6_Loadcell_ActLoad',
    'Leg3_ChordC_Motor7_Loadcell_ActLoad',
    'Leg3_ChordC_Motor8_Loadcell_ActLoad',
    'Leg4_ChordA_Motor1_Loadcell_ActLoad',
    'Leg4_ChordA_Motor2_Loadcell_ActLoad',
    'Leg4_ChordA_Motor3_Loadcell_ActLoad',
    'Leg4_ChordA_Motor4_Loadcell_ActLoad',
    'Leg4_ChordA_Motor5_Loadcell_ActLoad',
    'Leg4_ChordA_Motor6_Loadcell_ActLoad',
    'Leg4_ChordA_Motor7_Loadcell_ActLoad',
    'Leg4_ChordA_Motor8_Loadcell_ActLoad',
    'Leg4_ChordB_Motor1_Loadcell_ActLoad',
    'Leg4_ChordB_Motor2_Loadcell_ActLoad',
    'Leg4_ChordB_Motor3_Loadcell_ActLoad',
    'Leg4_ChordB_Motor4_Loadcell_ActLoad',
    'Leg4_ChordB_Motor5_Loadcell_ActLoad',
    'Leg4_ChordB_Motor6_Loadcell_ActLoad',
    'Leg4_ChordB_Motor7_Loadcell_ActLoad',
    'Leg4_ChordB_Motor8_Loadcell_ActLoad',
    'Leg4_ChordC_Motor1_Loadcell_ActLoad',
    'Leg4_ChordC_Motor2_Loadcell_ActLoad',
    'Leg4_ChordC_Motor3_Loadcell_ActLoad',
    'Leg4_ChordC_Motor4_Loadcell_ActLoad',
    'Leg4_ChordC_Motor5_Loadcell_ActLoad',
    'Leg4_ChordC_Motor6_Loadcell_ActLoad',
    'Leg4_ChordC_Motor7_Loadcell_ActLoad',
    'Leg4_ChordC_Motor8_Loadcell_ActLoad'
  )
GROUP BY tagname
ORDER BY tagname;

SELECT
  tagname,
  COUNT(*) AS row_count
FROM timeseries.v_raw
WHERE timestamp_utc >= TIMESTAMP '2025-06-29 00:00:00'
  AND timestamp_utc <= TIMESTAMP '2025-06-29 23:59:59'
  AND tagname IN (
    'Leg1_ChordA_Motor1_Loadcell_ActLoad',
    'Leg1_ChordA_Motor2_Loadcell_ActLoad',
    'Leg1_ChordA_Motor3_Loadcell_ActLoad',
    'Leg1_ChordA_Motor4_Loadcell_ActLoad',
    'Leg1_ChordA_Motor5_Loadcell_ActLoad',
    'Leg1_ChordA_Motor6_Loadcell_ActLoad',
    'Leg1_ChordA_Motor7_Loadcell_ActLoad',
    'Leg1_ChordA_Motor8_Loadcell_ActLoad',
    'Leg1_ChordB_Motor1_Loadcell_ActLoad',
    'Leg1_ChordB_Motor2_Loadcell_ActLoad',
    'Leg1_ChordB_Motor3_Loadcell_ActLoad',
    'Leg1_ChordB_Motor4_Loadcell_ActLoad',
    'Leg1_ChordB_Motor5_Loadcell_ActLoad',
    'Leg1_ChordB_Motor6_Loadcell_ActLoad',
    'Leg1_ChordB_Motor7_Loadcell_ActLoad',
    'Leg1_ChordB_Motor8_Loadcell_ActLoad',
    'Leg1_ChordC_Motor1_Loadcell_ActLoad',
    'Leg1_ChordC_Motor2_Loadcell_ActLoad',
    'Leg1_ChordC_Motor3_Loadcell_ActLoad',
    'Leg1_ChordC_Motor4_Loadcell_ActLoad',
    'Leg1_ChordC_Motor5_Loadcell_ActLoad',
    'Leg1_ChordC_Motor6_Loadcell_ActLoad',
    'Leg1_ChordC_Motor7_Loadcell_ActLoad',
    'Leg1_ChordC_Motor8_Loadcell_ActLoad',
    'Leg2_ChordA_Motor1_Loadcell_ActLoad',
    'Leg2_ChordA_Motor2_Loadcell_ActLoad',
    'Leg2_ChordA_Motor3_Loadcell_ActLoad',
    'Leg2_ChordA_Motor4_Loadcell_ActLoad',
    'Leg2_ChordA_Motor5_Loadcell_ActLoad',
    'Leg2_ChordA_Motor6_Loadcell_ActLoad',
    'Leg2_ChordA_Motor7_Loadcell_ActLoad',
    'Leg2_ChordA_Motor8_Loadcell_ActLoad',
    'Leg2_ChordB_Motor1_Loadcell_ActLoad',
    'Leg2_ChordB_Motor2_Loadcell_ActLoad',
    'Leg2_ChordB_Motor3_Loadcell_ActLoad',
    'Leg2_ChordB_Motor4_Loadcell_ActLoad',
    'Leg2_ChordB_Motor5_Loadcell_ActLoad',
    'Leg2_ChordB_Motor6_Loadcell_ActLoad',
    'Leg2_ChordB_Motor7_Loadcell_ActLoad',
    'Leg2_ChordB_Motor8_Loadcell_ActLoad',
    'Leg2_ChordC_Motor1_Loadcell_ActLoad',
    'Leg2_ChordC_Motor2_Loadcell_ActLoad',
    'Leg2_ChordC_Motor3_Loadcell_ActLoad',
    'Leg2_ChordC_Motor4_Loadcell_ActLoad',
    'Leg2_ChordC_Motor5_Loadcell_ActLoad',
    'Leg2_ChordC_Motor6_Loadcell_ActLoad',
    'Leg2_ChordC_Motor7_Loadcell_ActLoad',
    'Leg2_ChordC_Motor8_Loadcell_ActLoad',
    'Leg3_ChordA_Motor1_Loadcell_ActLoad',
    'Leg3_ChordA_Motor2_Loadcell_ActLoad',
    'Leg3_ChordA_Motor3_Loadcell_ActLoad',
    'Leg3_ChordA_Motor4_Loadcell_ActLoad',
    'Leg3_ChordA_Motor5_Loadcell_ActLoad',
    'Leg3_ChordA_Motor6_Loadcell_ActLoad',
    'Leg3_ChordA_Motor7_Loadcell_ActLoad',
    'Leg3_ChordA_Motor8_Loadcell_ActLoad',
    'Leg3_ChordB_Motor1_Loadcell_ActLoad',
    'Leg3_ChordB_Motor2_Loadcell_ActLoad',
    'Leg3_ChordB_Motor3_Loadcell_ActLoad',
    'Leg3_ChordB_Motor4_Loadcell_ActLoad',
    'Leg3_ChordB_Motor5_Loadcell_ActLoad',
    'Leg3_ChordB_Motor6_Loadcell_ActLoad',
    'Leg3_ChordB_Motor7_Loadcell_ActLoad',
    'Leg3_ChordB_Motor8_Loadcell_ActLoad',
    'Leg3_ChordC_Motor1_Loadcell_ActLoad',
    'Leg3_ChordC_Motor2_Loadcell_ActLoad',
    'Leg3_ChordC_Motor3_Loadcell_ActLoad',
    'Leg3_ChordC_Motor4_Loadcell_ActLoad',
    'Leg3_ChordC_Motor5_Loadcell_ActLoad',
    'Leg3_ChordC_Motor6_Loadcell_ActLoad',
    'Leg3_ChordC_Motor7_Loadcell_ActLoad',
    'Leg3_ChordC_Motor8_Loadcell_ActLoad',
    'Leg4_ChordA_Motor1_Loadcell_ActLoad',
    'Leg4_ChordA_Motor2_Loadcell_ActLoad',
    'Leg4_ChordA_Motor3_Loadcell_ActLoad',
    'Leg4_ChordA_Motor4_Loadcell_ActLoad',
    'Leg4_ChordA_Motor5_Loadcell_ActLoad',
    'Leg4_ChordA_Motor6_Loadcell_ActLoad',
    'Leg4_ChordA_Motor7_Loadcell_ActLoad',
    'Leg4_ChordA_Motor8_Loadcell_ActLoad',
    'Leg4_ChordB_Motor1_Loadcell_ActLoad',
    'Leg4_ChordB_Motor2_Loadcell_ActLoad',
    'Leg4_ChordB_Motor3_Loadcell_ActLoad',
    'Leg4_ChordB_Motor4_Loadcell_ActLoad',
    'Leg4_ChordB_Motor5_Loadcell_ActLoad',
    'Leg4_ChordB_Motor6_Loadcell_ActLoad',
    'Leg4_ChordB_Motor7_Loadcell_ActLoad',
    'Leg4_ChordB_Motor8_Loadcell_ActLoad',
    'Leg4_ChordC_Motor1_Loadcell_ActLoad',
    'Leg4_ChordC_Motor2_Loadcell_ActLoad',
    'Leg4_ChordC_Motor3_Loadcell_ActLoad',
    'Leg4_ChordC_Motor4_Loadcell_ActLoad',
    'Leg4_ChordC_Motor5_Loadcell_ActLoad',
    'Leg4_ChordC_Motor6_Loadcell_ActLoad',
    'Leg4_ChordC_Motor7_Loadcell_ActLoad',
    'Leg4_ChordC_Motor8_Loadcell_ActLoad'
  )
GROUP BY tagname
ORDER BY tagname;

SELECT *
FROM timeseries.raw
WHERE timestamp_utc >= TIMESTAMP '2025-06-29 00:00:00'
  AND timestamp_utc <= TIMESTAMP '2025-06-29 23:59:59'
ORDER BY timestamp_utc DESC
LIMIT 50;
